#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

  set -euo pipefail

  # shellcheck source=.container/foundation/tools.d/b19-i18n
  . b19-i18n

  b19-prepare-volumes "${1:-/build.d/volumes.txt}"
